"""Shared paths, configuration, artifact registry and deterministic JSON for Phase 9 (API / Analytical Service).

Named p9common (the p3common / p8common convention): Phase 7 modules do `from common import ...`, so no Phase 9 module
reuses a Phase 7 or Phase 8 module name.

Phase 9 is READ-ONLY with respect to the source workbooks and Phases 1-8. It writes only to
  phase-09-api/{outputs,reports}   (regenerated by run_phase9.py --clean)
  the plant event store            (DALMIA_KILN_EVENTS_DB; never deleted by --clean)
The API process imports only this module, artifact_store and event_store: never Phase 7 / 8 code.

Configuration is split four ways:
  service      ServiceConfig (host, port, body limit)           environment variables below
  artifacts    ARTIFACTS (relative paths) + outputs/artifact_manifest.json (hashes)
  environment  DALMIA_KILN_POC_ROOT (project root)
  event store  DALMIA_KILN_EVENTS_DB (SQLite file)
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import re
from collections import Counter
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

VERSION = "p9-api-1.0.0"
API_PREFIX = "/api/v1"
DEFAULT_ROOT = Path(__file__).resolve().parents[2]


def project_root() -> Path:
    return Path(os.environ.get("DALMIA_KILN_POC_ROOT") or DEFAULT_ROOT).resolve()


ROOT = project_root()
PHASE_DIR = ROOT / "phase-09-api"
OUT = PHASE_DIR / "outputs"
REPORTS = PHASE_DIR / "reports"
DOCS = PHASE_DIR / "docs"
CONTRACT_FILE = PHASE_DIR / "config" / "analytical_contract.json"
MANIFEST_FILE = OUT / "artifact_manifest.json"
O2X_FILE = "phase-09-api/outputs/o2_excluded_scores.parquet"
SOURCE_ROOT = Path(os.environ.get("DALMIA_KILN_SOURCE_ROOT")
                   or "/home/admin1/POPOS-DATA/Codebases/Dalmia/Dalmia/Dalmia/AI Automation(Kiln)")


@dataclass(frozen=True)
class ServiceConfig:
    root: Path
    events_db: Path
    host: str = "127.0.0.1"          # loopback only by default: no unintended network exposure
    port: int = 8009
    max_body_bytes: int = 16_384

    @classmethod
    def from_env(cls) -> "ServiceConfig":
        root = project_root()
        return cls(root=root,
                   events_db=Path(os.environ.get("DALMIA_KILN_EVENTS_DB") or root / "phase-09-api/state/events.sqlite3"),
                   host=os.environ.get("DALMIA_KILN_API_HOST", "127.0.0.1"),
                   port=int(os.environ.get("DALMIA_KILN_API_PORT", "8009")))


# ============================================================================== artifact registry
# Every file the API reads. Clients never name a path: they name an endpoint, and the endpoint reads a fixed key here.
# The adapters read explicit column allow-lists (artifact_store): afr_context, phase4_context, historical_similarity,
# risk_score_diagnostics, post-event fields, W1-W5 flags, lead-time and coverage columns are never read.
def _a(key, path, phase, status, operational, note=""):
    return {"key": key, "path": path, "source_phase": phase, "analytical_status": status,
            "operational_status": operational, "note": note}


ARTIFACTS = (
    _a("risk_scores", "phase-07-risk-score/outputs/risk_scores.parquet", 7, "EMPIRICAL_POC", "OPERATIONAL_ROWS_ONLY",
       "only operational == True rows are served"),
    _a("risk_score_components", "phase-07-risk-score/outputs/risk_score_components.parquet", 7, "EMPIRICAL_POC",
       "OPERATIONAL_ROWS_ONLY"),
    _a("risk_score_confidence", "phase-07-risk-score/outputs/risk_score_confidence.parquet", 7, "EMPIRICAL_POC",
       "OPERATIONAL_ROWS_ONLY"),
    _a("risk_score_reasons", "phase-07-risk-score/outputs/risk_score_reasons.parquet", 7, "EMPIRICAL_POC",
       "OPERATIONAL_ROWS_ONLY"),
    _a("risk_score_reference", "phase-07-risk-score/outputs/risk_score_reference.json", 7, "FROZEN_REFERENCE",
       "METADATA"),
    _a("risk_score_bands", "phase-07-risk-score/outputs/risk_score_bands.csv", 7, "FROZEN_REFERENCE", "METADATA",
       "reference-relative bands, not plant alarm limits"),
    _a("risk_score_feature_inventory", "phase-07-risk-score/outputs/risk_score_feature_inventory.csv", 7,
       "FROZEN_REFERENCE", "METADATA"),
    _a("abnormal_episodes", "phase-06-abnormal-events/outputs/abnormal_episodes.parquet", 6,
       "KPI_DERIVED_EMPIRICAL", "HISTORICAL", "only in_final_set rows are served"),
    _a("p8_summary", "phase-08-early-warning/outputs/early_warning_summary.csv", 8, "HISTORICAL_VALIDATION",
       "HISTORICAL"),
    _a("p8_horizon", "phase-08-early-warning/outputs/early_warning_horizon_validation.csv", 8,
       "HISTORICAL_VALIDATION", "HISTORICAL", "coverage / lead-time columns are never read"),
    _a("p8_controls", "phase-08-early-warning/outputs/early_warning_control_validation.csv", 8,
       "HISTORICAL_VALIDATION", "HISTORICAL"),
    _a("p8_negative_controls", "phase-08-early-warning/outputs/early_warning_negative_controls.csv", 8,
       "HISTORICAL_VALIDATION", "HISTORICAL"),
    _a("p8_o2_sensitivity", "phase-08-early-warning/outputs/early_warning_o2_sensitivity.csv", 8,
       "HISTORICAL_VALIDATION", "HISTORICAL"),
    _a("p8_load_sensitivity", "phase-08-early-warning/outputs/early_warning_load_sensitivity.csv", 8,
       "HISTORICAL_VALIDATION", "HISTORICAL"),
    _a("p8_gates", "phase-08-early-warning/outputs/early_warning_validation.csv", 8, "HISTORICAL_VALIDATION",
       "HISTORICAL"),
    _a("p8_run_manifest", "phase-08-early-warning/outputs/run_manifest.json", 8, "PROVENANCE", "METADATA"),
    _a("p8_trajectories", "phase-08-early-warning/outputs/early_warning_trajectories.parquet", 8,
       "HISTORICAL_VALIDATION", "BUILD_VERIFICATION_ONLY",
       "read only by build_artifacts.py to verify the O2-excluded materialisation; never served"),
    _a("o2_excluded_scores", O2X_FILE, 9, "SENSITIVITY_ANALYSIS", "OPERATIONAL_ROWS_ONLY",
       "Phase 8 EXCLUDE_KILN_INLET_O2_ANALYSER VALIDATION_VARIANT, materialised once by Phase 8's unchanged code and "
       "verified against Phase 8's persisted values"),
    _a("analytical_contract", "phase-09-api/config/analytical_contract.json", 9, "CONTRACT", "METADATA",
       "machine-readable analytical state, limitations and plant data requirements"),
)
def artifact(key: str) -> dict:
    return next(a for a in ARTIFACTS if a["key"] == key)


# ============================================================================== hashing / JSON
def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fmt_ts(t) -> str | None:
    """Timestamps are timezone-naive in every artifact; they are emitted exactly, never converted."""
    if t is None or (isinstance(t, float) and math.isnan(t)) or str(t) in ("NaT", "nan", "None"):
        return None
    return t.strftime("%Y-%m-%dT%H:%M:%S") if isinstance(t, (datetime, date)) else str(t)


def clean(obj):
    """JSON-safe copy: NaN / inf -> None, numpy scalars -> Python, timestamps -> ISO strings."""
    if isinstance(obj, dict):
        return {str(k): clean(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [clean(v) for v in obj]
    if isinstance(obj, (datetime, date)):
        return fmt_ts(obj)
    if hasattr(obj, "item") and not isinstance(obj, (str, bytes)):   # numpy scalar
        obj = obj.item()
    if isinstance(obj, float):
        return obj if math.isfinite(obj) else None
    return obj


def dumps(obj) -> bytes:
    """Deterministic serialisation: sorted keys, no NaN, UTF-8."""
    return json.dumps(clean(obj), sort_keys=True, allow_nan=False, ensure_ascii=False,
                      separators=(",", ":")).encode("utf-8")


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj) -> None:
    """Atomic: a crash mid-write never leaves a half-written manifest behind."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(clean(obj), indent=1, sort_keys=True, allow_nan=False, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    os.replace(tmp, path)


def count(xs) -> dict:
    return dict(sorted(Counter(xs).items()))


REVIEW_HEADER = {"REVIEW_LOG.md": "| ID | Reviewer | Severity | Finding | Evidence | Action | Status | Revalidation |",
                 "PONYTAIL_AUDIT_REPORT.md": "| ID | Severity | Area | Location | Finding | Recommendation | Status | "
                                             "Resolution |"}


def review_rows(name: str) -> list[dict]:
    """Rows of a review table keyed by header; raises if the file's table header is not the expected one."""
    f = PHASE_DIR / "reviews" / name
    if not f.is_file():
        return []
    lines = f.read_text(encoding="utf-8").splitlines()
    header = REVIEW_HEADER[name]
    if header not in lines:
        raise ValueError(f"{name}: expected table header {header!r}")
    cols = [c.strip() for c in header.strip("|").split("|")]
    rows = [[c.strip() for c in ln.strip().strip("|").split("|")] for ln in lines
            if re.match(r"^\| [A-Z]+-[A-Z]*\d+ \|", ln)]
    bad = [r[0] for r in rows if len(r) != len(cols)]
    if bad:
        raise ValueError(f"{name}: rows with the wrong column count: {bad}")
    return [dict(zip(cols, r)) for r in rows]
