"""Writes reports/PHASE_9_API_ANALYTICAL_SERVICE_REPORT.md from the validation report, the manifest, the route
contract, the analytical contract and the review logs. Every number is read from those files; the prose is fixed."""
from __future__ import annotations

from p9common import CONTRACT_FILE, MANIFEST_FILE, OUT, REPORTS, VERSION, count, read_json, review_rows

NAME = "PHASE_9_API_ANALYTICAL_SERVICE_REPORT.md"


def write(r: dict) -> None:
    man, con = read_json(MANIFEST_FILE), read_json(CONTRACT_FILE)
    routes = read_json(OUT / "api_contract.json")["routes"]
    o2x, s, G = r["build"]["o2x"], r["service"], r["gates"]
    rev, pt = review_rows("REVIEW_LOG.md"), review_rows("PONYTAIL_AUDIT_REPORT.md")
    failed = [g for g, v in G.items() if v["result"] != "PASS"]
    status = "COMPLETE, awaiting review" if not failed else f"BLOCKED ({', '.join(failed)})"
    L = [f"# Phase 9 — API / Analytical Service Report ({VERSION})", "",
         f"**Status: {status}.** Generated by `scripts/run_phase9.py` (clean run: {r['clean_run']}).", ""]

    L += ["## 1. Executive summary", "",
          "Phase 9 is a read-only analytical service over the frozen Phase 6–8 artifacts, plus a plant event "
          "annotation store. The API exposes an empirical historical risk score derived from the POC analytical "
          "pipeline. Phase 8 did not support an early-warning claim against the available KPI-derived abnormal "
          "periods, so the service carries `early_warning_supported = false`, `alerting_enabled = false`, "
          "`prediction_enabled = false` and `plant_event_ground_truth_available = false` in its machine-readable "
          "contract, and a fixed `interpretation` block in every analytical response.", "",
          f"- {len(routes)} routes (stdlib WSGI, no new dependency); {r['tests_total']} tests; "
          f"{len(G) - len(failed)}/{len(G)} gates PASS.",
          f"- {len(man['artifacts'])} artifacts hash-verified at startup; the API answers 503 if any differs.",
          f"- The O₂-excluded variant is served from a one-time materialisation that reproduces Phase 8 exactly "
          f"({o2x['trajectory_rows_compared']} persisted values, max difference {o2x['trajectory_max_abs_diff']}; "
          f"rank correlation {o2x['rank_correlation_rebuilt']:.6f}, difference {o2x['rank_correlation_abs_diff']}).",
          "- Plant event annotations are independent ground-truth candidates supplied by the plant, stored with an "
          "append-only audit trail.", ""]

    L += ["## 2. Phase objective", "",
          "Provide a safe, traceable analytical API and a plant event annotation foundation for Phase 10, without "
          "turning the POC into an alerting or predictive system and without changing Phases 1–8.", ""]

    L += ["## 3. Architecture", "", "```text",
          "client ─▶ api_app.App (WSGI; ROUTES table; strict query / body validation; JSON request log)",
          "            ├─▶ artifact_store (hash-verified; column allow-lists; immutable in-memory views)",
          "            │      └─▶ Phase 6 / 7 / 8 artifacts + phase-09 O₂-excluded parquet (manifest SHA-256)",
          "            └─▶ event_store (SQLite: plant_events + append-only plant_event_audit)",
          "build_artifacts.py (offline child process) ─▶ O₂-excluded materialisation + artifact_manifest.json",
          "run_phase9.py ─▶ build ─▶ service checks ─▶ tests ─▶ determinism ─▶ gates ─▶ this report",
          "```", "",
          "One process, no framework and no new dependency (`wsgiref`, `sqlite3`, `json`). The API process never "
          "imports Phase 7 / 8 code; only the offline build step does, in a child process.", ""]

    L += ["## 4. API contract", "",
          "Envelope: `api_version`, `service_version`, `data`, `pagination` (collections), `provenance`, "
          "`interpretation` (prediction / alert / probability flags all false), `disclaimer`, `query`. Errors: "
          "`{error: {code, message, request_id, details}}` with 400 / 404 / 405 / 409 / 413 / 415 / 422 / 500 / 503. "
          "Full contract: `docs/API_CONTRACT.md`; generated route table: `outputs/api_contract.json`.", ""]

    L += ["## 5. Endpoint inventory", "", "| Method | Path | Kind | Summary |", "|---|---|---|---|"]
    L += [f"| {x['method']} | `{x['path']}` | {x['kind']} | {x['summary']} |" for x in routes] + [""]

    L += ["## 6. Artifact lineage", "", "| Key | Phase | Version | SHA-256 (12) | Status | = Phase 8 validated input |",
          "|---|---|---|---|---|---|"]
    L += [f"| {a['key']} | {a['source_phase']} | {a['version'] or '-'} | `{a['sha256'][:12]}` | "
          f"{a['analytical_status']} / {a['operational_status']} | {a['matches_phase8_validated_input']} |"
          for a in man["artifacts"]]
    L += ["", "Endpoint → adapter → artifact → phase mapping: `docs/DATA_LINEAGE.md`.", ""]

    L += ["## 7. Risk-score semantics", "",
          "`empirical_risk_score` is the frozen Phase 7 score (`p7-risk-1.1.0`, 0–100): resemblance to abnormal "
          "process behaviour relative to the Apr–May 2025 reference. Only `operational == True` rows are served. "
          "`reference_relative_band` (LOW / ELEVATED / HIGH) is a reference quantile band, not an alarm level. The "
          "O₂-excluded variant is a `SENSITIVITY_ANALYSIS` returned only for `variant=o2_excluded` or in the labelled "
          "comparison; neither variant is preferred.", ""]

    L += ["## 8. Phase 8 validation semantics", "",
          "`GET /api/v1/validation/early-warning-historical` returns Phase 8's historical results unchanged: primary "
          "endpoint `NOT_SUPPORTED` (PE +0.051, 95 % CI −0.087 to +0.119, p 0.118, Cliff's δ +0.21, 10 of 12 periods, "
          "6,641 controls); O₂-excluded `WEAK`; horizons; controls; negative controls; load `INSUFFICIENT_DATA`; "
          "censoring (6 of 12 onsets). W1–W5 appear only as historical classifications with `is_live_flag = false`; "
          "coverage, lead-time and alert-rate columns are not served. `tests/test_integrity.py` asserts these values "
          "against the Phase 8 artifacts.", ""]

    L += ["## 9. Event annotation model", "",
          "`plant_events`: event_id (UUID4), event_type (COATING, RING, DEPOSIT, CLEANING, MAINTENANCE, STOPPAGE, "
          "FEED_REDUCTION, ANALYSER_CALIBRATION, PROCESS_UPSET, OTHER), start_time, end_time (nullable), "
          "timestamp_basis, equipment, description, source, source_reference, severity, plant_confirmation, "
          "label_origin (always PLANT_SUPPLIED), status (ACTIVE / DELETED), version, created / updated at / by. The "
          "analytical layer never writes an annotation: `analytical_label` is always null, and `analytical_context` "
          "(overlapping KPI-derived periods) is computed on read and never stored. See `docs/EVENT_ANNOTATION.md`.", ""]

    L += ["## 10. Persistence design", "",
          "SQLite (stdlib), one short-lived connection per operation, `BEGIN IMMEDIATE` for writes, each mutation and "
          "its audit row in one transaction. Enforced by the database: enums, `end_time > start_time`, "
          "`label_origin = 'PLANT_SUPPLIED'`, no hard delete of events and an append-only audit table (triggers). "
          "Default file `phase-09-api/state/events.sqlite3` (gitignored; `DALMIA_KILN_EVENTS_DB`); `--clean` never "
          "deletes it.", ""]

    L += ["## 11. Security", "",
          "No route takes a path; artifact paths are fixed in code and hash-verified. Strict query parsing (unknown, "
          "repeated or empty → 400), JSON-only bodies ≤ 16 KiB, duplicate keys and NaN rejected, parameterised SQL, "
          "UUID-checked ids, control characters rejected, `X-Actor` attribution header, loopback bind by default, no "
          "stack trace or absolute path in any response. There is no authentication (documented limitation).", ""]

    L += ["## 12. Observability", "",
          "One JSON log line per request (request_id, timestamp, method, path, status, duration_ms; plus "
          "artifact_version, variant, query_window, result_count for analytical requests). Event descriptions and "
          "request bodies are not logged. `/health` is liveness; `/ready` requires verified artifacts and a reachable "
          "event store.", "",
          f"- startup {s['startup_seconds']} s; max RSS {s['max_rss_mb']} MB (validation process)",
          *[f"- {k}: {v} ms (median)" for k, v in s["latency_median"].items()],
          f"- loopback HTTP smoke test: {s['socket_smoke']}", ""]

    L += ["## 13. Testing", "", "| Suite | Tests | Result |", "|---|---|---|"]
    L += [f"| {k} | {v['ran']} | {'OK' if v['ok'] else 'FAILED'} |" for k, v in r["tests"].items()] + [""]

    ev = G["G11 DETERMINISM"]["evidence"]
    L += ["## 14. Determinism", "",
          f"G11 {G['G11 DETERMINISM']['result']}: {ev['compared']} files / query digests compared with the previous "
          f"clean run (previous run clean: {ev['previous_run_clean']}); differing: {ev['differing'] or 'none'}.", ""]

    L += ["## 15. Review findings", "",
          f"{len(rev)} logged findings; by reviewer {count(r['Reviewer'] for r in rev)}; by status "
          f"{count(r['Status'] for r in rev)}. "
          "Details: `reviews/REVIEW_LOG.md`.", ""]

    L += ["## 16. Ponytail audit", "",
          f"{len(pt)} findings; by status {count(r['Status'] for r in pt)}; G14 {G['G14 PONYTAIL']['result']}. "
          "Details: `reviews/PONYTAIL_AUDIT_REPORT.md`.", ""]

    L += ["## 17. Known limitations", ""] + [f"- **{x['topic']}** ({x['status']}): {x['detail']}"
                                              for x in con["limitations"]]
    L += ["- **NO_AUTHENTICATION**: `X-Actor` is attribution, not identity; keep the loopback bind or put an "
          "authenticating proxy in front before any shared deployment.",
          "- **SINGLE_THREADED_SERVER**: stdlib `wsgiref`; adequate for an analyst tool, not for concurrent users.", ""]

    L += ["## 18. Phase 10 handoff", "",
          "Phase 10 may consume: the historical risk score, the O₂-excluded overlay (`variant-comparison`), the "
          "KPI-derived abnormal periods, the Phase 8 validation findings, plant event annotations, metadata, "
          "provenance and data-quality status.", "",
          "Phase 10 must not: show live W1–W5 flags; use alarm colours for bands; show a prediction, deposit or "
          "failure probability; state lead times; show the Phase 7 AUC; treat Phase 9 as a live alerting source.", ""]

    L += ["## 19. Plant data requirements", ""] + [f"- P{x['priority']}: {x['data']} (unblocks {x['unblocks']})"
                                                   for x in con["plant_data_requirements"]]
    L += ["", f"Revalidation: re-run the frozen Phase 8 protocol once at least "
          f"{con['revalidation']['minimum_evaluable_events_for_revalidation']} evaluable plant-labelled events exist. "
          "That is a prerequisite for re-running the protocol, not a validation.", ""]

    L += ["## 20. Completion gates", "", "| Gate | Result |", "|---|---|"]
    L += [f"| {g} | {v['result']} |" for g, v in G.items()] + [""]
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / NAME).write_text("\n".join(L), encoding="utf-8")
